---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: simple-build
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: A simple build task
  params:
    - name: Dockerfile
      description: Path to a Dockerfile
      type: string
  steps:
    - name: build
      image: quay.io/konflux-ci/task-runner:latest
      script: |
        #!/bin/bash
        set -euo pipefail
        echo "Building ${IMAGE}"
