---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sast-crypto-scan
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    The sast-crypto-scan task uses [crypto-finder-image](https://github.com/rh-pvsec/crypto-finder-image) tool to perform Static Code Analysis in order to detect crypto assets being used.
    It reports crypto algorithms in a CycloneDX format (cbom.json).
  params:
    - name: TARGET_DIRS
      description: Target directories in component's source code. Multiple values should be separated with commas.
      type: string
      default: "."
    - name: SKIP_SBOM_GENERATION
      description: Skip SBOM-related operations. This will likely cause EC policies to fail if enabled
      type: string
      default: "false"
    - name: SCAN_TIMEOUT
      description: Timeout scan if it takes more than the time specified.
      type: string
      default: "30m"
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: image-url
      description: Image URL.
      type: string
      default: ""
    - name: image-digest
      description: Digest of the image to scan.
      type: string
      default: ""
  results:
    - name: TEST_OUTPUT
      description: Tekton task test output.
  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
    - name: bound-token
      projected:
        sources:
          - serviceAccountToken:
              audience: openshift
              expirationSeconds: 7200
              path: quay-token
  workspaces:
    - name: workspace
  steps:
    - name: pull-rules
      image: quay.io/konflux-ci/task-runner:2.1.0@sha256:c34c933c269e2401bb042fe69e2999cf288331b6586d4f4eca9c845270d9b1f9
      when:
        - input: "$(params.SKIP_SBOM_GENERATION)"
          operator: in
          values: [ "false" ]
      volumeMounts:
        - name: bound-token
          mountPath: /var/run/secrets/tokens
          readOnly: true
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        CONSOLE=$(oc whoami --show-console | sed -E 's|^https://console-openshift-console\.apps\.([^.:]*)\..*:?.*$|\1|')
        echo "Running on: $CONSOLE"

        if [[ "${CONSOLE}" =~ ^(kflux-prd-rh03|kflux-prd-rh02|kflux-prd-rh01|stone-prod-p02|stone-prod-p01|kflux-ocp-p01|kflux-rhel-p01|kflux-osp-p01|stone-stg-rh01|stone-stage-p01)$ ]] ; then
          # This unpinned image contain the latest rolling rules
          ADDITIONAL_RULES_IMAGE="quay.io/exd-guild-security/crypto-rules-image:latest"
          ROBOT_ACCOUNT="exd-guild-security+konflux_crypto_rules_pull"
        else
          echo "No ADDITIONAL_RULES_IMAGE set, and no supported cluster detected"
          exit 0
        fi

        REGISTRY_HOSTNAME=${ADDITIONAL_RULES_IMAGE%%/*}
        TOKEN=$(cat /var/run/secrets/tokens/quay-token)
        if [ -z "${TOKEN}" ]; then
          echo "No bound token available"
          exit 1
        fi

        SL_TOKEN=$(curl -s --fail \
          --user "${ROBOT_ACCOUNT}:${TOKEN}" \
          "https://${REGISTRY_HOSTNAME}/oauth2/federation/robot/token" \
          | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])')

        if [ -z "${SL_TOKEN}" ] ; then
          echo "Unable to authenticate to $REGISTRY_HOSTNAME with $ROBOT_ACCOUNT and bound token"
          exit 0
        fi

        export XDG_RUNTIME_DIR=/tmp/oc-run
        mkdir -p -m 0700 "${XDG_RUNTIME_DIR}"

        echo "About to download image ${ADDITIONAL_RULES_IMAGE}"
        oc registry login --registry="${REGISTRY_HOSTNAME}" --auth-basic="${ROBOT_ACCOUNT}:${SL_TOKEN}"

        mkdir /workspace/rules
        retry oc image extract "${ADDITIONAL_RULES_IMAGE}" --path="/rules/:/workspace/rules"

    - name: rh-crypto-scanner
      # TEST IMAGE, it should be stored under konflux-ci and pinned
      image: quay.io/exd-guild-security/crypto-finder-image:latest
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      volumeMounts:
        - name: trusted-ca
          mountPath: /mnt/trusted-ca
          readOnly: true
      env:
        - name: TARGET_DIRS
          value: $(params.TARGET_DIRS)
        - name: SCAN_TIMEOUT
          value: $(params.SCAN_TIMEOUT)
        - name: SKIP_SBOM_GENERATION
          value: $(params.SKIP_SBOM_GENERATION)
        - name: WORKSPACE_PATH
          value: $(workspaces.workspace.path)
        - name: BUILD_PLR_LOG_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pipelinesascode.tekton.dev/log-url']
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        echo "Using crypto-finder version:"
        crypto-finder version

        echo "Using opengrep version: $(opengrep  --version)"

        OUTPUT_FILE="cbom.json"
        SOURCE_CODE_DIR="${WORKSPACE_PATH}/source"

        # generate full path for each dirname separated by comma
        declare -a ALL_TARGETS
        IFS="," read -ra TARGET_ARRAY <<<"$TARGET_DIRS"
        for d in "${TARGET_ARRAY[@]}"; do
          potential_path="${SOURCE_CODE_DIR}/${d}"

          resolved_path=$(realpath -m "$potential_path")

          # ensure resolved path is still within SOURCE_CODE_DIR
          if [[ "$resolved_path" == "${SOURCE_CODE_DIR}/"* || "$resolved_path" == "$SOURCE_CODE_DIR" ]]; then
            ALL_TARGETS+=("$resolved_path")
          else
            echo "Error: path traversal attempt, '$potential_path' is outside '$SOURCE_CODE_DIR'"
            exit 1
          fi
        done

        # Generate rules arguments
        # This includes the open source rule sets provided by the image in /usr/local/rules
        # and the proprietary rules provided by previous step in /workspace/rules
        declare -a RULES_ARGUMENTS=()
        for d in /usr/local/rules/* /workspace/rules/*; do
          if [ -d "${d}" ] ; then
            echo "Adding '$(basename $d)' rules directory"
            RULES_ARGUMENTS+=("--rules-dir")
            RULES_ARGUMENTS+=("$d")
          fi
        done

        if [ "${SKIP_SBOM_GENERATION}" != "false" ]; then
          RESULT="SKIPPED"
          SUCCESSES="0"
          FAILURES="0"
        elif [ ${#RULES_ARGUMENTS[@]} -eq 0 ]; then
          echo "Error: no rules detected"
          RESULT="ERROR"
          SUCCESSES="0"
          FAILURES="1"
        else
          RESULT="SUCCESS"
          SUCCESSES="1"
          FAILURES="0"
          echo "Running crypto scanner on the specified targets"
          crypto-finder \
            scan \
            --no-remote-rules \
            "${RULES_ARGUMENTS[@]}" \
            --format cyclonedx \
            --timeout "${SCAN_TIMEOUT}" \
            "${ALL_TARGETS[@]}" > "${OUTPUT_FILE}"
        fi
        TEST_OUTPUT=$(echo "{\"result\":\"${RESULT}\",\"timestamp\":\"$(date -u --iso-8601=seconds)\",\"failures\":${FAILURES},\"successes\":${SUCCESSES},\"warnings\":0}")
        echo "${TEST_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
        echo "Task $(context.task.name) completed."
      computeResources:
        limits:
          cpu: "8"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 4Gi
    - name: upload
      image: quay.io/konflux-ci/oras:latest@sha256:da693a7dcbadafc9f4422ae6600b41b2847944f7f14c5622827d6f58c727cf08
      when:
        - input: "$(params.SKIP_SBOM_GENERATION)"
          operator: in
          values: [ "false" ]
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      volumeMounts:
        - mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
      env:
        - name: IMAGE_URL
          value: $(params.image-url)
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        if [ -z "${IMAGE_URL}" ] || [ -z "${IMAGE_DIGEST}" ]; then
          echo 'No image-url or image-digest param provided. Skipping upload.'
          exit 0
        fi

        UPLOAD_FILES="cbom.json"
        for UPLOAD_FILE in ${UPLOAD_FILES}; do
          if [ ! -f "${UPLOAD_FILE}" ]; then
            echo "No ${UPLOAD_FILE} exists. Skipping upload."
            continue
          fi

          # Determine the media type based on the file extension
          if [[ "${UPLOAD_FILE}" == *.json ]]; then
            MEDIA_TYPE="application/json"
          else
            MEDIA_TYPE="application/sarif+json"
          fi

          echo "Selecting auth"
          select-oci-auth "$IMAGE_URL" >"$HOME/auth.json"
          echo "Attaching to ${IMAGE_URL}"
          if ! retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}@${IMAGE_DIGEST}" "${UPLOAD_FILE}:${MEDIA_TYPE}"; then
            echo "Failed to attach ${UPLOAD_FILE} to ${IMAGE_URL}"
            exit 1
          fi
        done
      computeResources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
