---
base: ../../prefetch-dependencies/0.3/prefetch-dependencies.yaml
add:
  - use-source
  - create-source
  - create-prefetch
additionalSteps:
  - at: 0
    name: skip-ta
    image: registry.access.redhat.com/ubi9/ubi-minimal:9.7-1775623882@sha256:d91be7cea9f03a757d69ad7fcdfcd7849dba820110e7980d5e2a1f46ed06ea3b
    env:
    - name: INPUT
      value: $(params.input)
    - name: SOURCE_ARTIFACT
      value: $(params.SOURCE_ARTIFACT)
    script: |
      #!/bin/bash

      if [ -z "${INPUT}" ]; then
        mkdir -p /var/workdir/source
        mkdir -p /var/workdir/cachi2
        echo "true" > /var/workdir/source/.skip-trusted-artifacts
        echo "true" > /var/workdir/cachi2/.skip-trusted-artifacts
        echo -n "${SOURCE_ARTIFACT}" > "$(results.SOURCE_ARTIFACT.path)"
        echo -n "" > "$(results.CACHI2_ARTIFACT.path)"
      fi
description: Task that prefetches project dependencies for hermetic build.
preferStepTemplate: true
removeWorkspaces:
  - source
replacements:
  workspaces.source.path: /var/workdir
