---
base: ../../prefetch-dependencies/0.3/prefetch-dependencies.yaml
add:
  - use-source
  - create-source
  - create-prefetch
additionalSteps:
  - at: 0
    name: skip-ta
    image: registry.access.redhat.com/ubi9/ubi-minimal:9.8-1781496742@sha256:1bc3c5c15720506a0cf48adfdf8b623dfe704377e007d7bbae8d14876392ca6a
    env:
    - name: INPUT
      value: $(params.input)
    - name: SOURCE_ARTIFACT
      value: $(params.SOURCE_ARTIFACT)
    computeResources:
      limits:
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
    script: |
      #!/bin/bash

      if [ -z "${INPUT}" ]; then
        mkdir -p /var/workdir/source
        mkdir -p /var/workdir/cachi2
        echo "true" > /var/workdir/source/.skip-trusted-artifacts
        echo "true" > /var/workdir/cachi2/.skip-trusted-artifacts
        echo -n "${SOURCE_ARTIFACT}" > "$(results.SOURCE_ARTIFACT.path)"
        echo -n "" > "$(results.CACHI2_ARTIFACT.path)"
      fi
description: Task that prefetches project dependencies for hermetic build.
preferStepTemplate: true
removeWorkspaces:
  - source
replacements:
  workspaces.source.path: /var/workdir

useTAVolumeMount: true
