---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: opm-get-bundle-version
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: Fetch the current version of the provided OLM bundle image
  params:
    - name: bundle-image
      description: OLM bundle image to query
  results:
    - name: bundle-version
      description: olm.package version
  workspaces:
    - name: workspace
      description: The shared workspace between steps
  stepTemplate:
    imagePullPolicy: IfNotPresent
  steps:
    - name: opm-render-bundle
      image: "registry.redhat.io/openshift4/ose-operator-registry:latest@sha256:fb659a4c2942db5f1073c6b66be5c7ac2e4aed30432cce4aff08b9d5874010e9"
      computeResources:
        limits:
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        runAsUser: 0
      env:
        - name: BUNDLE_IMAGE
          value: $(params.bundle-image)
      script: |
        #!/usr/bin/env bash
        set -xe
        opm render "${BUNDLE_IMAGE}" > "$(workspaces.workspace.path)/bundle.json"
    - name: jq-get-olm-package-version
      image: "quay.io/konflux-ci/task-runner:1.8.1@sha256:b9ef0479b57a494368a12a02886c650314c9ac7391c6228f21065865aab71c9e"
      computeResources:
        limits:
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      script: |
        #!/usr/bin/env bash
        set -xe

        jq -jr \
          '.properties | .[] | select(.type == "olm.package") | .value.version' \
          "$(workspaces.workspace.path)/bundle.json" \
          > "$(results.bundle-version.path)"
