---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: opm-get-bundle-version
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: Fetch the current version of the provided OLM bundle image
  params:
    - name: bundle-image
      description: OLM bundle image to query
  results:
    - name: bundle-version
      description: olm.package version
  workspaces:
    - name: workspace
      description: The shared workspace between steps
  steps:
    - name: opm-render-bundle
      image: "registry.redhat.io/openshift4/ose-operator-registry:latest"
      securityContext:
        runAsUser: 0
      env:
        - name: BUNDLE_IMAGE
          value: $(params.bundle-image)
      script: |
        #!/usr/bin/env bash
        set -xe
        opm render "${BUNDLE_IMAGE}" > "$(workspaces.workspace.path)/bundle.json"
    - name: jq-get-olm-package-version
      image: "quay.io/konflux-ci/task-runner:1.6.0@sha256:1abfe4e50d4e961d0fd9790202565f93ee650fe8dfc50932c94989acba10485f"
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      script: |
        #!/usr/bin/env bash
        set -xe

        jq -jr \
          '.properties | .[] | select(.type == "olm.package") | .value.version' \
          "$(workspaces.workspace.path)/bundle.json" \
          > "$(results.bundle-version.path)"
