apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-test
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: "E2E Tests"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to run e2e tests
  params:
    - name: e2e_test_namespace
      type: string
    - name: app_suffix
      type: string
    - name: ec_pipelines_repo_url
      type: string
    - name: ec_pipelines_repo_revision
      type: string
    - name: artifact_dir
      type: string
    - name: pipelinerun_name
      type: string
    - name: revision
      type: string
    - name: scenarios
      type: string
      default: "basic"
  workspaces:
    - name: source
      description: Workspace containing the cloned repository
  volumes:
    - name: konflux-test-infra-volume
      secret:
        secretName: konflux-test-infra
  steps:
    - name: e2e-test
      image: quay.io/redhat-user-workloads/konflux-qe-team-tenant/konflux-e2e/konflux-e2e-tests:e0aca0804d10db527d21837f988ecce24c190556
      workingDir: $(workspaces.source.path)/source/e2e-tests
      script: |
        #!/bin/bash
        set -euo pipefail

        bundle_values="$(workspaces.source.path)/source/bundle_values.env"
        if [[ -f "${bundle_values}" ]]; then
          echo "Using custom bundles from ${bundle_values}"
          # shellcheck disable=SC1090
          source "${bundle_values}"
        else
          echo "No custom bundles found, using defaults"
        fi

        ginkgo build ./tests/build/
        ginkgo \
          --label-filter=build-templates-e2e \
          --fail-on-empty \
          --junit-report="${ARTIFACT_DIR}/e2e-report.xml" \
          --no-color \
          -v \
          --timeout=2h \
          ./tests/build/ 2>&1 | tee "${ARTIFACT_DIR}/e2e-tests.log"
      securityContext:
        capabilities:
          add:
          - SETFCAP
      onError: continue
      env:
      - name: ARTIFACT_DIR
        value: "$(params.artifact_dir)"
      - name: APP_SUFFIX
        value: "$(params.app_suffix)"
      - name: QUAY_E2E_ORGANIZATION
        value: redhat-appstudio-qe
      - name: E2E_APPLICATIONS_NAMESPACE
        value: "$(params.e2e_test_namespace)"
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github
            key: token
      - name: QUAY_TOKEN
        valueFrom:
          secretKeyRef:
            name: e2e-tests-quay-token
            key: token
      - name: MY_GITHUB_ORG
        value: konflux-qe-bd
      - name: EC_PIPELINES_REPO_URL
        value: "$(params.ec_pipelines_repo_url)"
      - name: EC_PIPELINES_REPO_REVISION
        value: "$(params.ec_pipelines_repo_revision)"
      - name: SCENARIOS
        value: "$(params.scenarios)"
      - name: TEKTON_CHAINS_NS
        value: "openshift-pipelines"
    - name: capture-log
      image: quay.io/konflux-ci/task-runner:1.6.0@sha256:1abfe4e50d4e961d0fd9790202565f93ee650fe8dfc50932c94989acba10485f
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      script: |
        #!/bin/bash
        set -euo pipefail
        echo "Storing e2e-tests pod log..."
        artifact_dir=$(params.artifact_dir)
        oc logs "$(params.pipelinerun_name)-e2e-tests-pod" --all-containers > "${artifact_dir}"/e2e-tests.log
    - name: secure-push-oci
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
      params:
        - name: workdir-path
          value: /workspace/artifact-dir
        - name: oci-ref
          value: quay.io/konflux-test-storage/konflux-team/build-definitions:$(params.revision)
        - name: credentials-volume-name
          value: konflux-test-infra-volume
    - name: fail-if-any-step-failed
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/fail-if-any-step-failed/0.1/fail-if-any-step-failed.yaml
