apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ko
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Image Build
    tekton.dev/tags: image-build
    tekton.dev/displayName: "Build and upload container image using ko"
    tekton.dev/platforms: "linux/amd64,linux/arm64"
spec:
  description: >-
    This Task builds source into a container image using ko.
  params:
    - name: BUILD_ARGS
      description: additional arguments to ko build
      type: string
      default: ""
    - name: CACHI2_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the prefetched dependencies.
      type: string
      default: ""
    - name: IMAGE
      description: Reference of the image ko will produce.
    - name: KO_DEFAULTBASEIMAGE
      description: base image for ko build
      default: ""
    - name: KO_IMAGE
      description: ko image to use for builds
      default: "quay.io/redhat-user-workloads/konflux-build-pipeli-tenant/ko-builder:127e70d57df2a6b75bf3a2bb233a6223fb6a8cab"
    - name: MAIN
      description: import path of package main
      default: "."
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the
        CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built
    - name: IMAGE_REF
      description: Image reference of the built image
    - name: IMAGE_URL
      description: Image repository and tag where the built image was pushed
    - name: SBOM_BLOB_URL
      description: Reference of SBOM blob digest to enable digest-based verification from provenance
  volumes:
    - name: trusted-ca
      configMap:
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        name: $(params.caTrustConfigMapName)
        optional: true
    - name: workdir
      emptyDir: {}
  stepTemplate:
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:edd8e3affc389320b15b9de8a5aedbf7b0463211b77c981563a2cfa20076b0c0
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
        - $(params.CACHI2_ARTIFACT)=/var/workdir/cachi2
      volumeMounts:
        - name: trusted-ca
          mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          readOnly: true
          subPath: ca-bundle.crt
    - name: build
      image: $(params.KO_IMAGE)
      workingDir: /var/workdir/source
      env:
        - name: DOCKER_CONFIG
          value: "/opt/app-root/src/.docker"
        - name: KO_DEFAULTBASEIMAGE
          value: "$(params.KO_DEFAULTBASEIMAGE)"
        - name: GOFLAGS
          value: "-buildvcs=false"
      volumeMounts:
        - name: trusted-ca
          mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          readOnly: true
          subPath: ca-bundle.crt
      script: |
        #!/bin/bash
        set -euo pipefail

        # Note: component value should equal the base name of MAIN.
        export KO_DOCKER_REPO=$(dirname "$(params.IMAGE)")
        base=$(basename "$(params.IMAGE)")
        component="${base%:*}"
        tag="${base##*:}"

        args="-B $(params.BUILD_ARGS) -t ${tag}"
        ko build ${args} $(params.MAIN) 2>&1 | tee build.log

        digest=$(grep Published build.log | grep -v SBOM | awk '{print $4}' | awk -F@ '{print $2}')
        url=$(grep Publishing build.log | awk '{print $4}')
        ref="${url}@${digest}"
        sbom=$(grep SBOM build.log | awk '{print $5}')

        echo "IMAGE_DIGEST=${digest}"
        echo "IMAGE_REF=${ref}"
        echo "IMAGE_URL=${url}"
        echo "SBOM_BLOB_URL=${sbom}"

        echo -n "${digest}" > "$(results.IMAGE_DIGEST.path)"
        echo -n "${url}@${digest}" > "$(results.IMAGE_REF.path)"
        echo -n "${url}" > "$(results.IMAGE_URL.path)"
        echo -n "${sbom}" > "$(results.SBOM_BLOB_URL.path)"
        echo "Completed."
