---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-script
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, konflux
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: |-
    This task allows to run an script stored on the git repository and stores the resultant directory
    to use it later.
  params:
    - name: enableSymlinkCheck
      description: |
        Check symlinks in the repo. If they're pointing outside of the repo, the build will fail.
      type: string
      default: "true"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: ""
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: SCRIPT_RUNNER_IMAGE
      description: The image to run the script in
      type: string
    - name: SCRIPT
      description: The script to launch
      type: string
    - name: SCRIPT_WORKDIR
      description: The directory to launch the script from
      type: string
      default: /var/workdir/script
    - name: SCRIPT_ARTIFACT_DIRECTORY
      description: The directory to include on the output Trusted Artifact
      type: string
      default: /var/workdir/script
    - name: STORAGE_DRIVER
      description: Storage driver to configure for buildah
      type: string
      default: vfs
    - name: HERMETIC
      description: Determines if build will be executed without network access.
      type: string
      default: "false"
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the
        CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
  results:
    - name: SCRIPT_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
    - name: SCRIPT_BASE_IMAGE
      description: Reference and digest of the image used to run the script. Suitable to pass to buildah ADDITIONAL_BASE_IMAGES
      type: string
    - name: SCRIPT_OUTPUT
      description: The output string of the script
      type: string
    - name: SCRIPT_OUTPUT_ARRAY
      description: The output array of the script
      type: array
  volumes:
    - name: trusted-ca
      configMap:
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        name: $(params.caTrustConfigMapName)
        optional: true
    - name: workdir
      emptyDir: {}
    - name: varlibcontainers
      emptyDir: {}
  stepTemplate:
    computeResources:
      limits:
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
    env:
      - name: SCRIPT
        value: $(params.SCRIPT)
      - name: HERMETIC
        value: $(params.HERMETIC)
      - name: SOURCE_CODE_DIR
        value: source
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
      volumeMounts:
        - mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
    - name: run-script
      image: quay.io/konflux-ci/buildah-task:latest@sha256:ab0ba3b70f99faa74d2dd737422a965197af4922dec0109113bc535a94db0dfd
      args:
        - $(params.SCRIPT)
      workingDir: /var/workdir
      volumeMounts:
        - mountPath: /mnt/trusted-ca
          name: trusted-ca
          readOnly: true
        - mountPath: /var/lib/containers
          name: varlibcontainers
      env:
        - name: SCRIPT_WORKDIR
          value: $(params.SCRIPT_WORKDIR)
        - name: SCRIPT_RUNNER_IMAGE
          value: $(params.SCRIPT_RUNNER_IMAGE)
        - name: STORAGE_DRIVER
          value: $(params.STORAGE_DRIVER)
      script: |
        #!/bin/bash
        set -euo pipefail
        ca_bundle=/mnt/trusted-ca/ca-bundle.crt
        if [ -f "$ca_bundle" ]; then
          echo "INFO: Using mounted CA bundle: $ca_bundle"
          cp -vf $ca_bundle /etc/pki/ca-trust/source/anchors
          update-ca-trust
        fi

        # Fixing group permission on /var/lib/containers
        chown root:root /var/lib/containers

        sed -i 's/^\s*short-name-mode\s*=\s*.*/short-name-mode = "disabled"/' /etc/containers/registries.conf

        # Setting new namespace to run buildah - 2^32-2
        echo 'root:1:4294967294' | tee -a /etc/subuid >>/etc/subgid

        UNSHARE_ARGS=()
        if [ "${HERMETIC}" == "true" ]; then
          echo "The script will be executed with network isolation"
          UNSHARE_ARGS+=("--net")
        fi

        cp -r /var/workdir/source /var/workdir/script
        mkdir /var/workdir/output
        buildah from --name script-container "$SCRIPT_RUNNER_IMAGE"
        BUILDAH_CMD="buildah run --volume /var/workdir/script:/var/workdir/script --volume /var/workdir/output:/var/workdir/output --workingdir ${SCRIPT_WORKDIR} --user root:root -- script-container $*"
        unshare -Uf "${UNSHARE_ARGS[@]}" --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 -w /var/workdir sh -c "${BUILDAH_CMD}"

        IMAGE_REFERENCE=$(buildah inspect script-container | jq -r '.FromImage + "@" + .FromImageDigest')
        echo -n "$IMAGE_REFERENCE" > "$(results.SCRIPT_BASE_IMAGE.path)"

        if [ -f "/var/workdir/output/output" ]; then
          cat /var/workdir/output/output > "$(results.SCRIPT_OUTPUT.path)"
        fi
        if [ -f "/var/workdir/output/array" ]; then
          cat /var/workdir/output/array > "$(results.SCRIPT_OUTPUT_ARRAY.array)"
        fi
      securityContext:
        capabilities:
          add:
            - SETFCAP
    - name: symlink-check
      image: quay.io/konflux-ci/git-clone@sha256:4e53ebd9242f05ca55bfc8d58b3363d8b9d9bc3ab439d9ab76cdbdf5b1fd42d9
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
      env:
        - name: PARAM_ENABLE_SYMLINK_CHECK
          value: $(params.enableSymlinkCheck)
        - name: CHECKOUT_DIR
          value: $(params.SCRIPT_ARTIFACT_DIRECTORY)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        check_symlinks() {
          FOUND_SYMLINK_POINTING_OUTSIDE_OF_REPO=false
          while read -r symlink; do
            target=$(readlink -m "$symlink")
            if ! [[ "$target" =~ ^$CHECKOUT_DIR ]]; then
              echo "The script output directory contains symlink pointing outside of the directory: $symlink"
              FOUND_SYMLINK_POINTING_OUTSIDE_OF_REPO=true
            fi
          done < <(find "$CHECKOUT_DIR" -type l -print)
          if [ "$FOUND_SYMLINK_POINTING_OUTSIDE_OF_REPO" = true ]; then
            return 1
          fi
        }

        if [ "${PARAM_ENABLE_SYMLINK_CHECK}" = "true" ]; then
          echo "Running symlink check"
          check_symlinks
        fi
    - name: fix-permissions
      image: quay.io/konflux-ci/buildah-task:latest@sha256:ab0ba3b70f99faa74d2dd737422a965197af4922dec0109113bc535a94db0dfd
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
      env:
        - name: CHECKOUT_DIR
          value: $(params.SCRIPT_ARTIFACT_DIRECTORY)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        chown -R root:root "$CHECKOUT_DIR"
      securityContext:
        runAsUser: 0
    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.SCRIPT_ARTIFACT.path)=$(params.SCRIPT_ARTIFACT_DIRECTORY)
      volumeMounts:
        - mountPath: /var/workdir
          name: workdir
        - mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
      computeResources:
        limits:
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 3Gi
