---
base: ../../git-clone/0.2/git-clone.yaml
removeParams:
  - deleteExisting
  - subdirectory
addEnvironment:
  - name: KBC_GIT_CLONE_OUTPUT_DIR
    value: /var/workdir
  - name: KBC_GIT_CLONE_SUBDIRECTORY
    value: source
add:
  - create-source
useTAVolumeMount: true
removeWorkspaces:
  - output
description: The git-clone-oci-ta Task will clone a repo from the provided url and store it as a trusted
    artifact in the provided OCI repository.
