---
name: yamllint
"on":
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
      - name: Lint YAML files
        run: yamllint .
